#lang scheme
(define (nearest_number a b n)
  (if (< (abs (- a n)) (abs (- b n))) a b)) 
(define (fib n)
  (define (it a b k)
    (if (= k 0) b (it b (+ a b) (- k 1))))
  (it 1 1 (- n 1)))
(define (nearest_fib number)
  (define (iter n)
    (if (>= (fib n) number ) (nearest_number (fib n) (fib (- n 1)) number)
        (iter (+ n 1))))
  (iter 1))
(nearest_fib 6)
(nearest_fib 8)
(nearest_fib 12)
